name: 'bug_template'
description: '버그 발생 시 제보해주세요.'
title: '[BUG] '
labels:
  - 'bug'
assignees:
  - 'assignee'

body:
  - type: markdown
    attributes:
      value: "## 🐞 버그 설명\n\n발생한 버그에 대한 간단한 설명을 작성해주세요."
  - type: textarea
    attributes:
      label: '📋 상세 설명'
      placeholder: '버그가 발생한 상황을 자세히 설명해주세요.'
  - type: textarea
    attributes:
      label: '🔍 재현 방법'
      placeholder: '버그를 재현할 수 있는 방법을 단계별로 설명해주세요.'
  - type: markdown
    attributes:
      value: "## 📸 참고 자료\n\n스크린샷 또는 추가 자료가 있다면 첨부해주세요."
  - type: markdown
    attributes:
      value: "## 🚀 진행 상황\n\n- [ ] 분석 중\n- [ ] 수정 중\n- [ ] 테스트 완료"
