name: 'etc_template'
description: '기타 건의사항을 작성해주세요.'
title: '[건의 사항]'
labels:
  - 'etc'
assignees:
  - 'assignee'

body:
  - type: markdown
    attributes:
      value: "## ✨ 건의 사항\n\n건의하고 싶은 내용을 간단히 설명해주세요."
  - type: textarea
    attributes:
      label: '📋 상세 설명'
      placeholder: '구체적인 내용을 자세히 설명해주세요.'
  - type: markdown
    attributes:
      value: "## 📸 참고 자료\n\n스크린샷이나 자료가 있으면 첨부해주세요."
  - type: markdown
    attributes:
      value: "## 🚀 진행 상황\n\n- [ ] 검토 중\n- [ ] 진행 중\n- [ ] 완료"
