name: 'feature_template'
description: '기능 개발 이슈 템플릿'
title: '[FEAT] '
labels:
  - 'feature'
assignees:
  - 'assignee'

body:
  - type: markdown
    attributes:
      value: "## 🔧 작업 개요\n\n작업할 내용을 간단히 설명해주세요."
  - type: textarea
    attributes:
      label: '📋 상세 설명'
      placeholder: '구체적인 내용을 작성해주세요.'
  - type: markdown
    attributes:
      value: "## 📝 작업 내용\n\n1. 작업1\n2. 작업2\n3. 작업3"
  - type: markdown
    attributes:
      value: "## 📸 참고 자료\n\n필요 시 스크린샷이나 자료를 첨부해주세요."
  - type: markdown
    attributes:
      value: "## 🚀 진행 상황\n\n- [ ] 작업1\n- [ ] 작업2\n- [ ] 작업3"
